## Limpieza de datos
Importamos pandas y leemos nuestra data inicial

In [14]:
import pandas as pd

pd.set_option('display.max_rows', 10)   
pd.set_option('display.max_columns', 10)

raw_data = pd.ExcelFile("../data/raw/datos-siniestros.xlsx")

Extraemos la hoja que vamos a analizar y echamos un vistazo a como esta organizada la informacion

In [15]:
df = pd.read_excel(raw_data, sheet_name = 'Base Consolidada')
pd.DataFrame(df)

,No. IPAT,No. Caso,A. Información IPAT,Unnamed: 3,Unnamed: 4,...,Unnamed: 1007,Unnamed: 1008,Unnamed: 1009,Unnamed: 1010,Unnamed: 1011
0,NaN,NaN,1. Organismos de tránsito,2. Gravedad,3. Lugar o coordenadas geográficas,...,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,Código de la ruta,...,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,...,B5,B6,B7,B8,B9
3,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
100,A001455930,140,BOGOTÁ,CON HERIDO,*****,...,*****,*****,*****,*****,*****
101,A001393715,141,11001,CON MUERTO,*****,...,*****,*****,*****,APLICA,*****
102,A001517489,E001,BOGOTÁ,CON MUERTO,*****,...,*****,*****,*****,*****,*****
103,A001516649,E002,*****,CON MUERTO,*****,...,*****,*****,*****,*****,*****
104,A001518226,E003,*****,CON MUERTO,*****,...,*****,*****,*****,*****,*****

In [19]:
df = df.dropna(subset='No. IPAT')
df = df.reset_index(drop=True)
pd.DataFrame(df)

,No. IPAT,No. Caso,A. Información IPAT,Unnamed: 3,Unnamed: 4,...,Unnamed: 1007,Unnamed: 1008,Unnamed: 1009,Unnamed: 1010,Unnamed: 1011
5,A001390447,1,POLICÍA DE TRÁNSITO,CON HERIDO,*****,...,*****,*****,*****,*****,*****
6,A001392146,3,POLICIA DE TRANSITO,CON MUERTO,*****,...,*****,*****,*****,*****,*****
7,A001392548,4,POLICIA DE TRANSITO,CON MUERTO,*****,...,*****,*****,*****,*****,*****
8,A001394622,5,POLICÍA DE TRÁNSITO,CON MUERTO,*****,...,*****,*****,*****,*****,*****
9,A001394061,6,POLICÍA DE TRÁNSITO,CON MUERTO,*****,...,*****,*****,*****,*****,*****
...,...,...,...,...,...,...,...,...,...,...,...
100,A001455930,140,BOGOTÁ,CON HERIDO,*****,...,*****,*****,*****,*****,*****
101,A001393715,141,11001,CON MUERTO,*****,...,*****,*****,*****,APLICA,*****
102,A001517489,E001,BOGOTÁ,CON MUERTO,*****,...,*****,*****,*****,*****,*****
103,A001516649,E002,*****,CON MUERTO,*****,...,*****,*****,*****,*****,*****
104,A001518226,E003,*****,CON MUERTO,*****,...,*****,*****,*****,*****,*****